theme: jekyll-theme-minimal
title: On Pages
description: Basic intro on how to create and deploy simple webpages to report your results
logo: images/logo.png
author: Ieva Rauluseviciute
show_downloads: true
google_analytics:
plugins:
  - jemoji