remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: On Pages
description: Basic intro on how to create and deploy simple webpages to report your results
logo: images/logo.png
author: Ieva Rauluseviciute
show_downloads: true
google_analytics:
plugins:
  - jemoji